### ISSUE TITLE
Make lint fails on xenial

### ISSUE THREAD

**Issue by lazypower** [battlemidget/juju-layer-nginx#11]
charles@failbowl:~/builds/kubeapi-load-balancer$ make lint

```
ERROR: invocation failed (errno 2), args: ['/home/charles/builds/kubeapi-load-balancer/.tox/py27/bin/pip', 'freeze'], cwd: /home/charles/builds/kubeapi-load-balancer
Traceback (most recent call last):
  File "/usr/local/bin/tox", line 11, in <module>
    sys.exit(cmdline())
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 39, in main
    retcode = Session(config).runcommand()
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 375, in runcommand
    return self.subcommand_test()
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 540, in subcommand_test
    action=action)
  File "/usr/local/lib/python2.7/dist-packages/tox/venv.py", line 362, in _pcall
    redirect=redirect, ignore_ret=ignore_ret)
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 136, in popen
    stdout=stdout, stderr=STDOUT)
  File "/usr/local/lib/python2.7/dist-packages/tox/session.py", line 224, in _popen
    stdout=stdout, stderr=stderr, env=env)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
Makefile:17: recipe for target 'lint' failed
make: *** [lint] Error 1
```

This appears to be related to how linting is setup in the makefile and tox. These are both independently maintained in layer-basic. I wonder if we shouldn't crib from their files and not setup a custom tox/makefile?

**Comment by adam-stokes** [comment]
Thanks fixed
